stages:
  - Test

test_screenshot_storybook:
  stage: Test
  image: node:18.16-bullseye-slim
  services:
    - docker:cli
  script:
    - node -v
    - npm -v
    - echo "Installing dependencies..."
    - npm install
    - npm run test:ui:ci
