stages:
  - Test

test_screenshot_storybook:
  stage: Test
  image: ubuntu:latest
  services:
    - node:17.4.0
    - npm:8.3.1
  script:
    - node -v
    - npm -v
    - echo "Installing dependencies..."
    - apt-get update && apt-get -y upgrade
    - apt-get install -y wget
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt-get install -y ./google-chrome-stable_current_amd64.deb
    - apt-get install -y nodejs
    - apt-get install -y npm
    - npm install
    - npm ci
    - npm run test:ui:ci
