stages:
  - Test

test_screenshot_storybook:
  stage: Test
  image: ubuntu:latest
  script:
    - echo "Installing dependencies..."
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install ./google-chrome-stable_current_amd64.deb
    - npm ci
    - npm run test:ui:ci
