stages:
  - lint
  - build
  - test
  - deploy

test_project:
  stage: test
  image: node:17.4.0
  script:
    - echo "Installing dependencies..."
    - npm install
    - npm test

build_project_prod:
  stage: build
  image: node:17.4.0
  script:
    - npm install
    - npm run build:prod

linting_typescript:
  stage: lint
  image: node:17.4.0
  script:
    - npm install
    - npm run lint:ts
