stages:
  - Test

test_screenshot_storybook:
  stage: Test
  image: yukinying/chrome-headless-browser
  services:
    - node:latest
  script:
    - node -v
    - npm -v
    - echo "Installing dependencies..."
    - npm install
    - npm run test:ui:ci
