stages:
  - Test

test_screenshot_storybook:
  stage: Test
  image: node:18.16-bullseye-slim
  script:
    - apt-get update && apt-get -y upgrade
    - apt-get install docker.io -y
    - echo "Installing dependencies..."
    - docker run hello-world
    - npm ci
    - npm run test:ui:ci
