stages:
  - Prepare
  - Lint
  - Build
  - Test
  - Deploy

prepare_dependencies:
  stage: Prepare
  image: node:17.4.0
  script:
    - echo "Installing dependencies..."
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week

test_project_unit:
  stage: Test
  script:
    - npm run test:unit

build_project_prod:
  stage: Build
  script:
    - npm run build:prod

linting_typescript:
  stage: Lint
  script:
    - npm run lint:ts

linting_css:
  stage: Lint
  script:
    - npm run lint:scss
