stages:
  - Test

test_screenshot_storybook:
  stage: Test
  image: ubuntu:latest
  script:
    - echo "Installing dependencies..."
    - apt-get install wget
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - dpkg -i google-chrome-stable_current_amd64.deb && apt-get install -f
    - npm ci
    - npm run test:ui:ci
