stages:
  - Prepare
  - Lint
  - Build
  - Test
  - Deploy

prepare_dependencies:
  stage: Prepare
  image: node:17.4.0
  script:
    - npm ci

test_project_unit:
  stage: Test
  image: node:17.4.0
  script:
    - echo "Installing dependencies..."
    - npm ci
    - npm run test:unit

test_screenshot:
  stage: Test
  image: node:17.4.0
  script:
    - echo "Installing dependencies..."
    - npm ci
    - npm run test:ui:ci

build_project_prod:
  stage: Build
  image: node:17.4.0
  script:
    - npm ci
    - npm run build:prod

build_storybook:
  stage: Build
  image: node:17.4.0
  script:
    - npm ci
    - npm run storybook:build

linting_typescript:
  stage: Lint
  image: node:17.4.0
  script:
    - npm ci
    - npm run lint:ts

linting_css:
  stage: Lint
  image: node:17.4.0
  script:
    - npm ci
    - npm run lint:scss
